apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-truck
  description: "A simple truck leasing hello world app"
  annotations:
      github.com/project-slug: rlbth/Backstage-hello-world-app
      backstage.io/dockerfile: ./Dockerfile
      backstage.io/techdocs-ref: url:./
spec:
  type: service
  lifecycle: experimental
  system: fleet-leasing
  owner: lakran
