apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-truck
  description: "A simple truck leasing hello world app"
  metadata:
    annotations:
      backstage.io/github-actions-id: rlbth/Backstage-hello-world-app
      backstage.io/dockerfile: ./Dockerfile
      backstage.io/techdocs-ref: url:https://github.com/rlbth/Backstage-hello-world-app/blob/main/README.md
spec:
  type: service
  lifecycle: experimental
  system: fleet-leasing
  owner: lakran
