apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app
  description: "A simple Hello World application with Docker"
  metadata:
    annotations:
      backstage.io/dockerfile: ./Dockerfile
      backstage.io/docker-image-repo: <docker-image-repository-url>
spec:
  type: service
  lifecycle: experimental
  owner: your-team-name
