apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-truck
  description: "A simple truck leasing hello world app"
  metadata:
    annotations:
      backstage.io/dockerfile: ./Dockerfile
      backstage.io/techdocs-ref: value
spec:
  type: service
  lifecycle: experimental
  owner: lakran
