AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to Create an S3 Bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName

Parameters:
  BucketName:
    Type: String
    Description: hello-truck-bucket.

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3Bucket
