name: Docker Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lakran/hello-world-app .

      # If pushing to Docker Hub
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lakran/hello-world-app

      # Add steps for deployment (localhost in this case - runs the bash script)
      - name: Deploy to Local Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@local-server-ip 'bash -s' < deploy-local.sh
