name: Docker Build and Deploy with CloudFormation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lakran/hello-truck .

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lakran/hello-truck

      - name: Deploy CloudFormation Template
        run: |
          aws cloudformation deploy \
            --template-file ./infrastructure/deployment-ecs.yaml \
            --stack-name hello-truck-ecs \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
