name: Docker Build and Deploy with CloudFormation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lakran/hello-truck .

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lakran/hello-truck

      - name: Deploy CloudFormation Stack for S3 Bucket
        id: deploy-s3-bucket
        run: |
          aws cloudformation deploy \
            --template-file ./infrastructure/s3-bucket-template.yaml \
            --stack-name my-s3-bucket-stack \
            --parameter-overrides BucketName=hello-truck-${{ github.run_id }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Retrieve the output from the deployed CloudFormation stack
      - name: Get S3 Bucket Name
        id: get-bucket-name
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name my-s3-bucket-stack --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text)
          echo "S3 Bucket Name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload CloudFormation Template to S3
        run: |
          aws s3 cp ./infrastructure/deployment-cft.yaml s3://${{ steps.cf-output.outputs.bucket }}/deployment-cft.yaml
        env:
          BUCKET_NAME: ${{ steps.deploy-s3-bucket.outputs.BucketName }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Deploy CloudFormation Template
        run: |
          aws cloudformation deploy \
            --template-file s3://$BUCKET_NAME/deployment-cft.yaml \
            --stack-name hello-truck-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
