name: Docker Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lakran/hello-truck .

      # If pushing to Docker Hub
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lakran/hello-truck

      - name: Upload CloudFormation Template to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          source: ./infrastructure/deployment-cft.yaml
          path: infrastructure/deployment-cft.yaml
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: Deploy CloudFormation Template
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: hello-truck-stack
          template: ./infrastructure/deployment-cft.yaml
          parameter-overrides: >-
            DockerHubUsername=${{ secrets.DOCKER_USERNAME }}
            DockerHubPassword=${{ secrets.DOCKER_PASSWORD }}
            DockerImage=lakran/hello-truck:latest
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: '1'